# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seasonalyze' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seasonalyze

  target 'seasonalyzeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'seasonalyzeUITests' do
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'  

end
